apiVersion: batch/v1
kind: Job
metadata:
  name: seed-job
spec:
  template:
    spec:
      containers:
        - name: seed-postgres
          image: postgres:17
          command:  ["sh", "-c"]
          args: 
            - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f migrations/seed.sql 
          env:
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: seed-sql
              mountPath: /migrations
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: seed-sql
          configMap:
            name: seed-config