apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:8
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongo-secret
          - configMapRef:
              name: mongo-config
        volumeMounts: 
        - name: custom-user
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: custom-user
          configMap:
            name: custom-user
            defaultMode: 0755